plugins {
    id 'java'
}

group = 'me.getsouf'
version = '1.0.0'

repositories {
    mavenCentral()
    maven {
        name = 'papermc'
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
    maven {
        name = 'codemc'
        url = 'https://repo.codemc.io/repository/maven-public/'
    }
    maven {
        name = 'jitpack'
        url = 'https://jitpack.io'
    }
}

dependencies {
    // Если TLS/сеть ломается — положи jar в libs/ (см. README ниже)
    def libsDir = file('libs')
    if (libsDir.exists()) {
        compileOnly fileTree(dir: 'libs', include: ['*.jar'])
    }

    compileOnly 'io.papermc.paper:paper-api:26.1.2.build.74-stable'
    compileOnly 'com.github.MilkBowl:VaultAPI:1.7.1'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}

jar {
    archiveFileName.set("BookHunt-${project.version}.jar")
}